### ISSUE TITLE
Unable to type as keyboard is locked

### ISSUE THREAD

**Issue by JeevanNaikOP** [galasa-dev/projectmanagement#1288] opened 2022-11-30 07:12 UTC
## Steps to reproduce
1. while using VTP to test CICS  screen, VTP manager and CICSTS manager creates terminal named <CICSTS$$>_1 and <CICSTS$$>_2.
2. <CICSTS$$>_2 starts right after clearing CICS welcome screen from  <CICSTS$$>_1, but keyboard of <CICSTS$$>_2 is  locked at that time.
3. VTP manager tries to type BZUT <transaction name> in <CICSTS$$>_2, which will throw KeyboardLockedException with message "Unable to type as keyboard is locked".

## Expected behavior
VTP manager and CICSTS manager should use different terminals.

**Comment by hobbit1983** [comment] 2022-12-01 09:55
The cause of this problem is that in VtpTxnRecorderImpl:startRecordingUsingTxn we assume that the terminal will be in the correct state.  Most of the time this will be correct but if there is increased latency between the test engine and the endpoint and/or decreased path length in any @Before methods this might not be the case.  We need to wait for the terminal to be ready and also increase the logging in this area to make future problems easier to diagnose.

Assigning to current Sprint

**Comment by hobbit1983** [comment] 2022-12-07 15:08
https://github.com/galasa-dev/managers/pull/834 raised for this issue.  Placing this issue into review

**Closed** 2022-12-08 09:13 UTC
Labels: defect
