### ISSUE TITLE
Finish development of SemCicsImpl

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#987] opened 2022-03-15 11:38 UTC
The following methods need to be developed. When used they throw "Not developed yet" exceptions:
- getUssHome
- getJvmProfileDir
- getJavaHome

**Comment by jadecarino** [comment] 2024-02-12 16:20
@eamansour FYI - duplicate of your story I believe.

**Comment by eamansour** [comment] 2024-02-22 10:06
Thanks Jade. Closing this as a duplicate of https://github.com/galasa-dev/projectmanagement/issues/1515

**Closed by eamansour** 2024-02-22 10:06 UTC
Labels: 2-digital debt
