### ISSUE TITLE
Eclipse laucher needs to be updated for each new release

### ISSUE THREAD

**Issue by DavidXRoberts** [galasa-dev/projectmanagement#63] opened 2020-01-07 15:07 UTC
The Eclipse launcher includes the launch parameter:
`--obr mvn:dev.galasa/dev.galasa.uber.obr/_version_/obr`
where version needs to be updated for each release/snapshot

**Comment by Michael-Baylis** [comment] 2020-01-17 10:12
duplicate of #56

**Closed by Michael-Baylis** 2020-01-17 10:12 UTC
