### ISSUE TITLE
Boot - Authentication

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#473] opened 2020-11-17 10:47 UTC
Provide the abilitiy for Boot to provide authentication when retrieving maven artifacts

**Comment by techcobweb** [comment] 2024-01-02 08:31
Closing this issue as it's a duplicate of [Galasa needs to load test artifacts from a password-protected maven repo#1572](https://github.com/galasa-dev/projectmanagement/issues/1572)

**Closed by techcobweb** 2024-01-02 08:31 UTC
Labels: Epic, 5-Framework, Deliverable
