### ISSUE TITLE
Galasactl way of creating initial Galasa Managers

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#1908] opened 2024-06-26 10:28 UTC
## Story
As a Galasa test developer, I want to be able to initialise a new Galasa Manager Java project, so that I can have a starting point to quickly begin manager development \<benefit>.

## Background
I would like something equivalent to
```galasactl project create```
for Galasa managers that will initialise a manager project with the required package structure (e.g. internal, properties folders) and some example classes of each type.

**Comment by techcobweb** [comment] 2024-07-01 09:57
This appears to be a duplicate of this story: [CLI create project --manager creates a manager module #1410](https://github.com/galasa-dev/projectmanagement/issues/1410)

**Closed** 2024-07-01 09:58 UTC
