### ISSUE TITLE
Error while executing test script -ERROR dev.galasa.framework.TestRunner.runTest - Unable to load the test bundle dev.galasa.simbank.tests

### ISSUE THREAD

**Issue by Shalini174** [galasa-dev/projectmanagement#250] opened 2020-05-04 09:22 UTC
I was able to run all the test cases(for SimBank) few days back, but now all the tests are failing with below error:

ERROR dev.galasa.framework.TestRunner.runTest - Unable to load the test bundle dev.galasa.simbank.tests
dev.galasa.framework.spi.FrameworkException: Unable to install bundle "dev.galasa.simbank.tests" from OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:45)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:217)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:104)
Caused by: dev.galasa.framework.spi.FrameworkException: Unable to install bundles outside of resolver
	at dev.galasa.framework.BundleManagement.addResource(BundleManagement.java:111)
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:43)
	... 8 more
Caused by: org.osgi.framework.BundleException: Bundle symbolic name and version are not unique: dev.galasa.framework.maven.repository.spi:0.7.0
	at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1337)
	at org.apache.felix.framework.BundleImpl.<init>(BundleImpl.java:113)
	at org.apache.felix.framework.Felix.installBundle(Felix.java:3260)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:120)
	at dev.galasa.framework.BundleManagement.addResource(BundleManagement.java:103)
	... 9 more
04/05/2020 13:35:39.212 ERROR dev.galasa.boot.Launcher.launch - Unable to run test class
dev.galasa.boot.LauncherException: java.lang.NullPointerException
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:219)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:104)
Caused by: java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at dev.galasa.framework.spi.FrameworkPropertyFile.set(FrameworkPropertyFile.java:230)
	at dev.galasa.framework.internal.dss.FpfDynamicStatusStore.put(FpfDynamicStatusStore.java:55)
	at dev.galasa.framework.internal.dss.FrameworkDynamicStoreKeyAccess.put(FrameworkDynamicStoreKeyAccess.java:55)
	at dev.galasa.framework.TestRunner.updateResult(TestRunner.java:480)
	at dev.galasa.framework.TestRunner.updateStatus(TestRunner.java:462)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:217)
	... 2 more

Please suggest.

**Comment by Michael-Baylis** [comment] 2020-05-05 08:04
Hi,  I've been hitting a similar problem recently and I think I know what the problem is.
I suspect the Eclipse plugin and the version of the OBR are different,  not that it should matter really.  Would you try upgrading your plugin to 0.7.0 and try again.  If I am right, your plugin will be 0.6.0 or earlier and in your eclipse preferences for galasa,  the OBR version will be blank or set to "latest".

**Comment by Michael-Baylis** [comment] 2020-05-05 08:12
I have raised issue #253 to fix this.   But the workaround in the previous comment should help.  (it's what I do when I ecounter this problem)

**Comment by Shalini174** [comment] 2020-05-06 11:11
Hi @Michael-Baylis : the eclipse preference for Galasa has blank and Galasa plugin is v0.6.0. But when i try to update the plugin from eclipse, it is giving below error:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,dev.galasa,0.7.0
No repository found containing: osgi.bundle,dev.galasa.cps.etcd,0.7.0
No repository found containing: osgi.bundle,dev.galasa.eclipse,0.7.0.202004301033
No repository found containing: osgi.bundle,dev.galasa.framework,0.7.0
No repository found containing: osgi.bundle,dev.galasa.ras.couchdb,0.7.0
No repository found containing: osgi.bundle,dev.galasa.simbank.ui,0.7.0.202004301055
No repository found containing: osgi.bundle,dev.galasa.zos3270.common,0.7.0
No repository found containing: osgi.bundle,dev.galasa.zos3270.ui,0.7.0.202004301040
No repository found containing: org.eclipse.update.feature,dev.galasa.eclipse.feature,0.7.0.202004301033
No repository found containing: org.eclipse.update.feature,dev.galasa.simbank.feature,0.7.0.202004301055
No repository found containing: org.eclipse.update.feature,dev.galasa.zos.feature,0.7.0.202004301040

**Comment by Michael-Baylis** [comment] 2020-05-06 12:20
Eclipse has a nasty habbit of caching the update sites on startup.   Would you bounce the eclipse and try the update again please.

**Comment by Shalini174** [comment] 2020-05-07 11:34
Hi @Michael-Baylis : The issue is resolved now and my test cases are running fine with v0.7.0.  i wanted to check if there is a way we can store the test results (the screens tested) also.

**Comment by Michael-Baylis** [comment] 2020-05-07 11:41
If you are referring to the 3270 screens via the ITerminal,  they are automatically recorded as part of the test results.  You can replay them by looking at the run result.  Are you aware on how to do that?

**Comment by Shalini174** [comment] 2020-05-07 12:36
@Michael-Baylis : No, please let me know how we can replay them and where are they stored.

**Comment by Michael-Baylis** [comment] 2020-05-27 08:55
You can access previous local runs from within Eclipse, with the following steps:-

1. In the Eclipse menu there should be a "Galasa" entry, under that is Initialise Galasa Framework, select that.
1. On the toolbar there is a Galasa icon,  click that and that should open 2 new views, Galasa Runs and Galasa Results.
1. You need the Galasa Results view.
1. In the view should be "Local" and a set of time ranges.  within those will be the local test runs.
1. Double click on one of the runs, this will bring up what we call the "Run Editor" (not really a editor)
1. This gives you an overview of the test run.   Under the Stored Artifact tab, should be a tree for zos3270 if the test run had a terminal. expand this all the way.
1. Double click on one of the terminals,  this should provide you with a replay.

**Comment by Michael-Baylis** [comment] 2020-06-04 11:58
I assume all is ok with this,  so closing for now.   If there is still an issue,  please comment.

**Closed by Michael-Baylis** 2020-06-04 11:58 UTC
Labels: bug
