### ISSUE TITLE
As Galasa Admin I need an option to pass credentials to galasa ecosystem to pull OBRs from external repository like JFrog

### ISSUE THREAD

**Issue by haripra86** [galasa-dev/projectmanagement#1907] opened 2024-06-20 15:20 UTC
At present there is no way to pass credentials to Galasa ecosystem so it can pull OBR from private artifactories like JFrog etc.
We need this option so we can host code on safe repositories.

I see 401 auth response while submitting tests.

`java.io.IOException: Server returned HTTP response code: 401 for URL: https://na.xxxxxx.xxxx/zapm-tests/ibm.zaiops.zapm.tests.obr/0.0.1-SNAPSHOT/maven-metadata.xml`

This needs to be prioritised as it will compell admin to create and maintain a unsecured artifactories just to make galasa system work while IBM provides more secured artifactories.

**Comment by techcobweb** [comment] 2024-07-09 10:11
This is a duplicate of https://github.com/galasa-dev/projectmanagement/issues/1572
Closing, but adding more detail to that story.

**Closed by techcobweb** 2024-07-09 10:11 UTC
