### ISSUE TITLE
IVT tests need to work before we ship 0.25

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1312] opened 2023-01-04 15:40 UTC
The tests need to work before the 0.25 release can be shipped.

- [x] Investigate and fix issues if possible, else raise defects as required

**Comment by jadecarino** [comment] 2023-01-04 16:41
Error message from the tests:
```
04/01/2023 06:05:14.461 TRACE main dev.galasa.framework.BundleManagement.loadBundle - Installing bundle dev.galasa.inttests
04/01/2023 06:05:14.464 TRACE main dev.galasa.framework.BundleManagement.addResource - Resouce: dev.galasa.inttests/0.25.0
04/01/2023 06:05:14.517 ERROR main dev.galasa.framework.BundleManagement.addResource - Unable to resolve dev.galasa.inttests/0.25.0
04/01/2023 06:05:14.517 ERROR main dev.galasa.framework.BundleManagement.addResource - Unsatisfied requirement: package:(&(package=dev.galasa.common)(version>=0.25.0)(!(version>=1.0.0)))
04/01/2023 06:05:14.518 ERROR main dev.galasa.framework.BundleManagement.addResource - Unsatisfied requirement: package:(&(package=dev.galasa.zos3270)(version>=0.25.0)(!(version>=1.0.0)))
04/01/2023 06:05:14.518 ERROR main dev.galasa.framework.BundleManagement.addResource - Unsatisfied requirement: package:(&(package=dev.galasa.cicsts)(version>=0.24.0)(!(version>=1.0.0)))
04/01/2023 06:05:14.518 ERROR main dev.galasa.framework.BundleManagement.addResource - Unsatisfied requirement: package:(&(package=dev.galasa.zos3270.spi)(version>=0.25.0)(!(version>=1.0.0)))
04/01/2023 06:05:14.519 ERROR main dev.galasa.framework.TestRunner.runTest - Unable to load the test bundle dev.galasa.inttests
dev.galasa.framework.spi.FrameworkException: Unable to install bundle "dev.galasa.inttests" from OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:55) ~[-1672812311937:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:222) [-1672812311937:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.framework.spi.FrameworkException: Unable to resolve bundle dev.galasa.inttests
	at dev.galasa.framework.BundleManagement.addResource(BundleManagement.java:176) ~[-1672812311937:?]
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:53) ~[-1672812311937:?]
	... 8 more
```

I think that the problem is dev.galasa.common was added to the managers which zos3270 depends on, and in turn cicsts depends on, but dev.galasa.common was not added to release.yaml so was not exported as part of the OBR. I have added it to release.yaml of managers, and will run a test again to hopefully confirm the fix shortly.

**Comment by jadecarino** [comment] 2023-01-05 15:08
Issue with the inttests bundle not resolving is now fixed after correcting the snakeyaml version in the OBR and adding dev.galasa.common to release.yaml. The tests are beginning to build however are failing and provision discarding because there is a problem somewhere in the SSL code. Eamonn is currently working on a fix.

**Comment by jadecarino** [comment] 2023-01-06 14:34
Defects raised and being fixed for the failing tests.

**Closed by jadecarino** 2023-01-06 14:35 UTC
