### ISSUE TITLE
zOS Manager Documentation Links Not Appearing Correctly

### ISSUE THREAD

**Issue by matthewchivers** [galasa-dev/projectmanagement#712] opened 2021-05-24 15:37 UTC
There are some sections on the[ zOS Manager documentation](https://galasa.dev/docs/managers/zos-manager) that look like they should be formatting as a link, but are not. e.g. `{@link IZosFileHandler#newDataset(String, dev.galasa.zos.IZosImage)}` 

I believe it should possibly, be formatting like so: `@IZosFileHandler#newDataset(String, dev.galasa.zos.IZosImage)` so I am unsure of why the `@link` may be there.

This can be seen when navigating (on the page linked to above) to the "Notes" field of any accordion item in the "Annotations" section.

**Comment by CaroMac** [comment] 2021-05-24 16:08
Thank you for spotting this. The problems appears to lie in file ZosConsole.java in the Manager repo from which the docs are autogenerated. There is a hashtag element in some of the {link} code eg {@Link IZosConsole#issueCommand(String, String)}  which is causing the problems with rendering. 

There is also a problem with the links out to the javadoc. The links in "See ZosConsole, IZosConsole and IZosConsoleCommand to find out more." point out to the snapshot of Javadoc, not the Javadoc. eg https://javadoc-snapshot.galasa.dev/dev/galasa/zosconsole/ZosConsole.html instead of https://javadoc.galasa.dev/dev/galasa/zosconsole/ZosConsole.html.

Will speak with Mike to discuss resolution.

**Comment by hobbit1983** [comment] 2021-05-24 21:15
The broken links are pointing to javadoc-snapshot.galasa.dev, which appears to not have the manager content. thus the link breaks.  Changing the domain in the URL to javadoc.galasa.dev works as intended.

Still investigating

**Comment by hobbit1983** [comment] 2021-05-24 21:35
note that the # is perfectly valid in this instance.  It is linking to the anchor within the HTML for the correct class element (method or variable) and is correct.  If it is causing problems with the render then that is a separate concern

I do note that the pipeline to generate the markdown from the javadoc comments has been disabled.  I wonder if this is due to the move to Gradle.

**Comment by hobbit1983** [comment] 2021-06-30 12:45
Just checked this in preparation for a docs review today and this problem is now resolved - so closing the issue

**Closed by hobbit1983** 2021-06-30 12:45 UTC
Labels: defect, documentation
