### ISSUE TITLE
Failed to provision docker container

### ISSUE THREAD

**Issue by ArpanaKulenur** [galasa-dev/projectmanagement#521] opened 2020-11-25 05:37 UTC
Hi,
I'm trying to start the docker container in my test. My test class looks like below:
@DockerContainer(image="library/httpd:latest", dockerContainerTag="httpd", start=true)
	public IDockerContainer container1;
	container1.start();

My cps.properties looks like below:
docker.engine.hostname=192.168.1.19
docker.engine.port=2375

When i tried to run, I’m getting following error:

24/11/2020 18:21:37.923 INFO  d.g.f.FrameworkInitialisation - Framework initialised
24/11/2020 18:21:38.225 INFO  d.g.f.TestRunner - Run test: com.example.tests.atests/MostBasicTest
24/11/2020 18:21:38.246 INFO  d.g.d.i.DockerManagerImpl - Docker manager intialised
24/11/2020 18:21:38.247 DEBUG d.g.f.TestRunManagers - The following Managers are active:-
24/11/2020 18:21:38.248 DEBUG d.g.f.TestRunManagers -    dev.galasa.docker.internal.DockerManagerImpl
24/11/2020 18:21:38.248 DEBUG d.g.f.TestRunManagers -    dev.galasa.http.internal.HttpManagerImpl
24/11/2020 18:21:38.249 DEBUG d.g.f.TestRunManagers - The following Managers are sorted in provisioning order:-
24/11/2020 18:21:38.249 DEBUG d.g.f.TestRunManagers -    dev.galasa.http.internal.HttpManagerImpl
24/11/2020 18:21:38.249 DEBUG d.g.f.TestRunManagers -    dev.galasa.docker.internal.DockerManagerImpl
24/11/2020 18:21:38.301 INFO  d.g.f.TestRunner - Starting Provision Generate phase
24/11/2020 18:21:38.302 INFO  d.g.d.i.DockerManagerImpl - Registering docker registries
24/11/2020 18:21:38.313 INFO  d.g.d.i.DockerManagerImpl - Finding all docker related annotations
24/11/2020 18:21:38.317 INFO  d.g.f.TestRunner - Provision Generate failed
dev.galasa.framework.spi.FrameworkException: Problem in provision generate for manager dev.galasa.docker.internal.DockerManagerImpl
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:465)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:403)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:337)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:220)
	at dev.galasa.boot.Launcher.launch(Launcher.java:152)
	at dev.galasa.boot.Launcher.main(Launcher.java:106)
Caused by: dev.galasa.docker.DockerManagerException: Failed to provision docker container tag: ctgtest
	at dev.galasa.docker.internal.DockerManagerImpl.provisionContainer(DockerManagerImpl.java:155)
	at dev.galasa.docker.internal.DockerManagerImpl.generateDockerContainer(DockerManagerImpl.java:135)
	at dev.galasa.docker.internal.DockerManagerImpl.generateDockerFields(DockerManagerImpl.java:219)
	at dev.galasa.docker.internal.DockerManagerImpl.provisionGenerate(DockerManagerImpl.java:193)
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:460)
	... 9 more
Caused by: dev.galasa.docker.DockerProvisionException: Unable to instantiate Docker Engine
	at dev.galasa.docker.internal.DockerEngineImpl.<init>(DockerEngineImpl.java:75)
	at dev.galasa.docker.internal.DockerEnvironment.buildDockerEngine(DockerEnvironment.java:239)
	at dev.galasa.docker.internal.DockerEnvironment.provisionDockerContainer(DockerEnvironment.java:116)
	at dev.galasa.docker.internal.DockerManagerImpl.provisionContainer(DockerManagerImpl.java:153)
	... 13 more
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 192.168.1.19:2375
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.checkChar(URI.java:3031)
	at java.net.URI$Parser.parse(URI.java:3047)
	at java.net.URI.<init>(URI.java:588)
	at dev.galasa.docker.internal.DockerEngineImpl.<init>(DockerEngineImpl.java:66)
	... 16 more
24/11/2020 18:21:38.741 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Stopping Felix framework

**Comment by Michael-Baylis** [comment] 2020-11-30 10:11
@Jimbo4794 Please find out why this exception is being thrown

**Comment by Jimbo4794** [comment] 2020-11-30 13:32
Hi @ArpanaKulenur 

I replicated this problem. The issue is that a scheme is expected on the URI passed to the docker engine. passing an IP like this should be a perfectly valid way of expressing the docker engine so I will push a change that allows none schemed endpoints to be passed (defaulting to http://)

The code should be live soon, but if you need this working right now, you can set:

```
docker.engine.hostname=http://192.168.1.19
```

Ill keep this item open until the code is live in the SNAPSHOT build

**Comment by Jimbo4794** [comment] 2020-12-08 15:26
Merged the changes this morning

**Closed by Jimbo4794** 2020-12-08 15:26 UTC
Labels: Manager: Docker, defect
