### ISSUE TITLE
ZosManagerBatchIVT failure

### ISSUE THREAD

**Issue by matthewchivers** [galasa-dev/projectmanagement#787] opened 2021-08-04 10:28 UTC
Failing regression test C3467. Failed on method: `dev.galasa.zos.manager.ivt.ZosManagerBatchIVT#submitJCLNoSteps`

Job is successfully submitted and does run, but then when fetching the return code - the result is a 404 not found `{"message":"No job with name 'GAL5ERUV' and id 'JOB57880' was found","status":"NOT_FOUND"}`. 

On a retry the job is then found: `{"jobName":"GALODUG6","owner":"JATP","jobId":"JOB57881","returnCode":"CC 0000","subsystem":"JES2","type":"JOB","executionClass":"A","phaseName":"Job is on the hard copy queue","status":"COMPLETION"}` 

However, when attempting to append `files` to the same api uri, the 404 not found is triggered again. Ultimately, the 404 not found continues with many more errors after the files are not found.

```
----------------------- ****************************************************************************************************
----------------------- *** Start of test method dev.galasa.zos.manager.ivt.ZosManagerBatchIVT#submitJCLNoSteps,type=Test
----------------------- ****************************************************************************************************
04/08/2021 07:39:00.903 DEBUG main dev.galasa.artifact.internal.BundleResourcesImpl.retrieveFile - Searching for artifact: resources/jcl/noSteps.jcl in bundle dev.galasa.zos.manager.ivt
04/08/2021 07:39:00.908 TRACE main dev.galasa.zosrseapi.internal.RseapiManagerImpl.getRseapis - Retrieving RSE API server MV2D
04/08/2021 07:39:01.073 DEBUG main dev.galasa.zosrseapi.internal.RseapiRestApiProcessor.getCurrentRseapiServer - Using RSE API server on MV2D https://winmvs2d.hursley.ibm.com:6800
04/08/2021 07:39:01.073 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.addCommonHeaders - Adding HTTP header: accept: */*
04/08/2021 07:39:01.075 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.postJson - Request: POST https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/string/
04/08/2021 07:39:01.076 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.postJson - body: 
{"jcl":"//GAL5ERUV JOB ,\n//         CLASS=A,\n//         MSGCLASS=A,\n//         MSGLEVEL=(1,1)\n/*JOBPARM SYSAFF=MV2D\n//DONOWT  JOB 19842411,,CLASS=M,MSGCLASS=H,         \n//  NOTIFY=&SYSUID,                                 \n//  MSGLEVEL=(1,1)                                  \n//COBOL  EXEC PGM=IEFBR14                           \n/*                                                  \n"}
04/08/2021 07:39:04.962 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.postJson - Response: HTTP/1.1 201  - POST https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/string/
04/08/2021 07:39:04.963 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.submitJob - {"jobName":"DONOWT","owner":"JATP","jobId":"JOB57880","returnCode":"CC 0000","subsystem":"JES2","type":"JOB","executionClass":"M","phaseName":"Job is on the hard copy queue","status":"COMPLETION"}
04/08/2021 07:39:04.963 INFO  main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.submitJob - JOB GAL5ERUV(JOB57880) Submitted
04/08/2021 07:39:04.963 INFO  main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.waitForJob - Waiting up to 300 second(s) for JOB57880 GAL5ERUV to complete
04/08/2021 07:39:04.963 DEBUG main dev.galasa.zosrseapi.internal.RseapiRestApiProcessor.getCurrentRseapiServer - Using RSE API server on MV2D https://winmvs2d.hursley.ibm.com:6800
04/08/2021 07:39:04.964 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.addCommonHeaders - Adding HTTP header: accept: */*
04/08/2021 07:39:04.964 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Request: GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.004 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Response: HTTP/1.1 404  - GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.005 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - {"message":"No job with name 'GAL5ERUV' and id 'JOB57880' was found","status":"NOT_FOUND"}
04/08/2021 07:39:05.005 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - JOBID=JOB57880 JOBNAME=GAL5ERUV NOT FOUND
04/08/2021 07:39:05.006 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - JOBID=JOB57880 JOBNAME=GAL5ERUV OWNER=null TYPE=null STATUS=NOTFOUND RETCODE=????
04/08/2021 07:39:05.006 DEBUG main dev.galasa.zosrseapi.internal.RseapiRestApiProcessor.getCurrentRseapiServer - Using RSE API server on MV2D https://winmvs2d.hursley.ibm.com:6800
04/08/2021 07:39:05.007 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.addCommonHeaders - Adding HTTP header: accept: */*
04/08/2021 07:39:05.007 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Request: GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.160 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Response: HTTP/1.1 200  - GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.161 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - {"jobName":"GALODUG6","owner":"JATP","jobId":"JOB57881","returnCode":"CC 0000","subsystem":"JES2","type":"JOB","executionClass":"A","phaseName":"Job is on the hard copy queue","status":"COMPLETION"}
04/08/2021 07:39:05.161 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - JOBID=JOB57880 JOBNAME=GAL5ERUV OWNER=JATP TYPE=JOB STATUS=OUTPUT RETCODE=CC 0000
04/08/2021 07:39:05.161 DEBUG main dev.galasa.zosrseapi.internal.RseapiRestApiProcessor.getCurrentRseapiServer - Using RSE API server on MV2D https://winmvs2d.hursley.ibm.com:6800
04/08/2021 07:39:05.161 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.addCommonHeaders - Adding HTTP header: accept: */*
04/08/2021 07:39:05.162 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Request: GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880/files
04/08/2021 07:39:05.229 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Response: HTTP/1.1 404  - GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880/files
04/08/2021 07:39:05.229 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.buildErrorString - {"message":"No job with name 'GAL5ERUV' and id 'JOB57880' was found","status":"NOT_FOUND"}
04/08/2021 07:39:05.229 ERROR main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.getOutput - Error Retrieve job output, HTTP Status Code 404 : HTTP/1.1 404 
status: NOT_FOUND
message: No job with name 'GAL5ERUV' and id 'JOB57880' was found
04/08/2021 07:39:05.230 DEBUG main dev.galasa.zosrseapi.internal.RseapiRestApiProcessor.getCurrentRseapiServer - Using RSE API server on MV2D https://winmvs2d.hursley.ibm.com:6800
04/08/2021 07:39:05.230 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.addCommonHeaders - Adding HTTP header: accept: */*
04/08/2021 07:39:05.230 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Request: GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.312 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Response: HTTP/1.1 404  - GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.313 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - {"message":"No job with name 'GAL5ERUV' and id 'JOB57880' was found","status":"NOT_FOUND"}
04/08/2021 07:39:05.313 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - JOBID=JOB57880 JOBNAME=GAL5ERUV NOT FOUND
04/08/2021 07:39:05.313 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - JOBID=JOB57880 JOBNAME=GAL5ERUV OWNER=null TYPE=null STATUS=NOTFOUND RETCODE=????
04/08/2021 07:39:05.314 DEBUG main dev.galasa.zosrseapi.internal.RseapiRestApiProcessor.getCurrentRseapiServer - Using RSE API server on MV2D https://winmvs2d.hursley.ibm.com:6800
04/08/2021 07:39:05.314 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.addCommonHeaders - Adding HTTP header: accept: */*
04/08/2021 07:39:05.314 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Request: GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.368 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Response: HTTP/1.1 404  - GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.369 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - {"message":"No job with name 'GAL5ERUV' and id 'JOB57880' was found","status":"NOT_FOUND"}
04/08/2021 07:39:05.369 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - JOBID=JOB57880 JOBNAME=GAL5ERUV NOT FOUND
04/08/2021 07:39:05.369 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - JOBID=JOB57880 JOBNAME=GAL5ERUV OWNER=null TYPE=null STATUS=NOTFOUND RETCODE=????
04/08/2021 07:39:05.369 DEBUG main dev.galasa.zosrseapi.internal.RseapiRestApiProcessor.getCurrentRseapiServer - Using RSE API server on MV2D https://winmvs2d.hursley.ibm.com:6800
04/08/2021 07:39:05.369 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.addCommonHeaders - Adding HTTP header: accept: */*
04/08/2021 07:39:05.370 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Request: GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.405 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.get - Response: HTTP/1.1 404  - GET https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.405 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - {"message":"No job with name 'GAL5ERUV' and id 'JOB57880' was found","status":"NOT_FOUND"}
04/08/2021 07:39:05.406 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - JOBID=JOB57880 JOBNAME=GAL5ERUV NOT FOUND
04/08/2021 07:39:05.406 TRACE main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.updateJobStatus - JOBID=JOB57880 JOBNAME=GAL5ERUV OWNER=null TYPE=null STATUS=NOTFOUND RETCODE=????
04/08/2021 07:39:05.406 INFO  main dev.galasa.zosbatch.rseapi.manager.internal.RseapiZosBatchJobImpl.saveOutputToResultsArchive - Archiving batch job GAL5ERUV(JOB57880) to /zosBatchJobs/submitJCLNoSteps/GAL5ERUV_JOB57880_UNKNOWN
04/08/2021 07:39:05.407 DEBUG main dev.galasa.zosrseapi.internal.RseapiRestApiProcessor.getCurrentRseapiServer - Using RSE API server on MV2D https://winmvs2d.hursley.ibm.com:6800
04/08/2021 07:39:05.407 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.addCommonHeaders - Adding HTTP header: accept: */*
04/08/2021 07:39:05.407 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.delete - Request: DELETE https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.444 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.delete - Response: HTTP/1.1 404  - DELETE https://winmvs2d.hursley.ibm.com:6800/rseapi/api/v1/jobs/GAL5ERUV/JOB57880
04/08/2021 07:39:05.445 INFO  main dev.galasa.framework.GenericMethodWrapper.invoke - Ending
----------------------- ****************************************************************************************************
----------------------- *** Failed - Test method dev.galasa.zos.manager.ivt.ZosManagerBatchIVT#submitJCLNoSteps,type=Test
----------------------- ****************************************************************************************************
```

**Comment by DavidXRoberts** [comment] 2021-08-04 16:24
Given that the test passes locally and under different Java version variations, my guess is that it's caused by a network error or a problem with the RSE API server itself.
The full logs show the actual failure in in the automatic archiving at test method. So I've delivered a fix for that.

Closing as fixed, but we should reopen or raise a new issue if it occurs again

**Closed by DavidXRoberts** 2021-08-04 16:24 UTC
Labels: Manager: zOS Batch
