### ISSUE TITLE
Blog & Video: How to run your first local test with the CLI

### ISSUE THREAD

**Issue by louisa-seers** [galasa-dev/projectmanagement#1655] opened 2023-11-28 15:51 UTC
## Story
As a user, I want to understand how to run my first local test.

## Background
Any additional information that would help to explain the story.

## Tasks
- [ ] Create blog and/or video to explain how to run a local CLI.

**Comment by techcobweb** [comment] 2024-01-22 14:04
duplicate of

**Closed** 2024-01-22 14:05 UTC
Labels: Promotion
