### ISSUE TITLE
Install issue - Unable to read repository at https://p2.galasa.dev/content.xml.

### ISSUE THREAD

**Issue by thebarge0** [galasa-dev/projectmanagement#135] opened 2020-03-11 15:04 UTC
I needed to switch to the suggested new Eclipse install.  Now when I try to install I get the above error.

When I look at the web content I do not see the content.xml file at that location.

Index of /
      Name                    Last modified      Size  Description
      artifacts.jar           2020-03-10 13:08  1.8K  
      artifacts.xml.xz        2020-03-10 13:08  1.6K  
      content.jar             2020-03-10 13:08   22K  
      content.xml.xz          2020-03-10 13:08  9.5K  
      features/               2020-03-10 13:13    -   
      git.hash                2020-03-10 13:13   40   
      p2.index                2020-03-10 13:08  172   
      plugins/                2020-03-10 13:13    -

**Comment by thebarge0** [comment] 2020-03-12 19:10
Update, I missed an error, Could this be a Certificate error?

Unable to read repository at https://p2.galasa.dev/content.xml.
Unable to read repository at https://p2.galasa.dev/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by thebarge0** [comment] 2020-03-12 20:01
I believe the issue is in the certificate somehow or something in the communication path.  I was able to download the files from the p2.galasa.dev to the local file system and that install worked.  Any suggestions on what to look for will be appreciated.

**Comment by Michael-Baylis** [comment] 2020-03-13 10:13
It has become apparent that older versions of Java do not have the Let's Encrypt root CA certificates in the default keystore.   We have been considering buying a static certificate for the websites to counter this problem,   and maybe for the code signing as well.  I think this #issue pushes us to actually do this.
Assigning to Will as he was going to do the research
@hobbit1983 When looking at this,   it maybe worth getting a certificate to cope with code signing as well.

**Comment by hobbit1983** [comment] 2020-03-13 12:31
Already started speaking with the right internal folk for us to procure a certificate that is signed by a more recognised CA than Let's Encrypt.  As I see it we need 3 certificates (or a signing cert so we can self sign) 
1 for galasa.dev (not wild carded)
1 for *.galasa.dev
and 1 for code signing.

Any others?

**Comment by Michael-Baylis** [comment] 2020-03-13 12:57
wont be able to get a signing cert,   far too legislation for that.
dont worry about a signing cert for now,  we are using the IBM global one for that.
so, 2 galasa.dev and *.galasa.dev.

**Comment by Michael-Baylis** [comment] 2020-07-01 07:07
I believe this can be closed down now?

**Comment by hobbit1983** [comment] 2020-07-06 13:58
Moving to in review until we have heard that the solution provided to lloyds is OK and then we can publicise

**Comment by Michael-Baylis** [comment] 2020-07-08 08:16
We are seing this at more and more sites.   The cause is the company firewall/proxies are intercepting the https requests and are substituting the official certificates with internal signed certificates to represent the external sites.   The company would force the internal CA certificates into the browsers on the employee workstations.
This allows the company to inspect the encrypted traffic, which is why you should never use personal banking or anything you want secret on intranets that adopt this policy, as your passwords etc are exposed to the company.
The reason that this affects Eclipse and any other Java program is the Java JVM maintains a list of CA certificates itself and doesn't use the OS CA list, don't know why.   
To solve this problem, all you need to do is add the company CA certificate to the Java JVM Keystore.

**Closed by Michael-Baylis** 2020-07-08 08:16 UTC
Labels: enhancement
